          -- Business Analysis Questions and Answers--


-- 1. Calculate the total revenue generated by each country?

      SELECT country,
	         SUM(quantity * unit_price) AS total_revenue
      FROM e_commerce
	  GROUP BY 1
	  ORDER BY 2 DESC;


-- 2. Identify the top 10 customers based on the highest total spending (excluding customers with null IDs)?

	  SELECT customer_id,
	         SUM(quantity*unit_price) AS total_spend
	  FROM e_commerce
	  WHERE customer_id IS NOT NULL
	  GROUP BY 1
	  ORDER BY 2 DESC
	  LIMIT 10;


-- 3. Analyze the month-over-month revenue growth to understand sales trends?

	  WITH monthly_sales AS(
	  SELECT EXTRACT(MONTH FROM invoice_date) AS month,
	     	 SUM(quantity*unit_price) AS total_revenue
 	  FROM e_commerce
	  GROUP BY 1)
	  SELECT month,total_revenue,
	         LAG(total_revenue) OVER(ORDER BY month),
			 total_revenue - LAG(total_revenue) OVER(ORDER BY month) AS difference
	  FROM monthly_sales;


-- 4. Find the products that have been ordered most frequently (highest count of invoice numbers)?

	  SELECT stock_code,COUNT(invoice_no) AS total_orders
	  FROM e_commerce
	  GROUP BY 1
	  ORDER BY 2 DESC;


-- 5. Calculate the average order value for the entire store?

	  SELECT ROUND(SUM(quantity*unit_price)/COUNT(DISTINCT invoice_no),2) AS average_order_value
	  FROM e_commerce;


-- 6. Determine the average quantity of items per invoice?

	  SELECT invoice_no,
	   		 ROUND(SUM(quantity)/COUNT(DISTINCT invoice_no),2) AS average_items
	  FROM e_commerce
	  GROUP BY 1
	  ORDER BY 2 DESC;


-- 7. Count the number of unique customers who have made more than one purchase?

	  SELECT customer_id,COUNT(DISTINCT invoice_no) AS number_of_count
	  FROM e_commerce
	  WHERE customer_id IS NOT NULL
	  GROUP BY 1
	  HAVING COUNT(DISTINCT invoice_no)>1
	  ORDER BY 2 DESC;


-- 8. Categorize orders into 'Morning', 'Afternoon', and 'Evening' shifts to identify peak business hours?

	  WITH time_cte AS(
	  SELECT *,
	         CASE WHEN EXTRACT(HOUR FROM invoice_date) <12 THEN 'Morning'
			      WHEN EXTRACT(HOUR FROM invoice_date) BETWEEN 12  AND 17 THEN 'Afternoon'
				  ELSE 'Evening'
				               END AS timing
	  FROM e_commerce)
	  SELECT timing,
	         COUNT(*) AS number_of_orders
	  FROM time_cte
	  GROUP BY 1
	  ORDER BY 2 DESC;


-- 9. List the top 5 products with the lowest total quantity sold?

	  SELECT stock_code,SUM(quantity) AS total_orders
	  FROM e_commerce
	  GROUP BY 1
	  ORDER BY 2
	  LIMIT 5;


-- 10. Categorize products into 'Budget' (< 10), 'Mid-Range' (10-50), and 'Premium' (> 50) and calculate the total revenue for each category.

	   WITH range_cte AS(
	   SELECT *,CASE WHEN unit_price <10 THEN 'Budget'
	               WHEN unit_price BETWEEN 10 AND 50 THEN 'Mid-Range'
				   ELSE 'Premium' END AS price_range
	   FROM e_commerce
	   WHERE quantity>0 AND unit_price>0)
	   SELECT price_range,
	          SUM(quantity*unit_price) AS total_revenue
	   FROM range_cte
	   GROUP BY 1
	   ORDER BY 2 DESC;

	   